### ISSUE TITLE
Link each day with a pdf file

### ISSUE THREAD

**Issue by thaqiftaher** [zatorck/jquery-bootstrap-year-calendar#1]
Hi,

I am wondering on how we can have the hyperlink on each day in the calendar. For instance, if i clicked certain date, it will link me to a pdf file. Since the html code is generated by the jquery function, is there any way to make this possible? 

Thanks.

**Comment by zatorck** [comment]
Hi @thaqiftaher 

I'm really sorry for late answer. 

Atm. I'm afraid it's impossible in only HTML way. 

But don't worry.  You can always use built-in event to do things like that. Checkout documentation for more info.

Regards
