### ISSUE TITLE
Rage Choose not work.

### ISSUE THREAD

**Issue by Hunter-Nomad** [zatorck/jquery-bootstrap-year-calendar#2]
Hi Piotr!
I test your library and detect  bug.
If I write " $('.calendar').on('jqyc.**rageChoose**', function (event) " selected start date and end date   not return. But if I write $('.calendar').on('jqyc.**dayChoose**', function (event) is return. With an error but return.

**Comment by zatorck** [comment]
Thank you mate. 

Actually you reported two diffrent bugs.

First one was a typo in docs - I changed it.
Second one was real bug, and now everything works (I hope 👍)

Regards

**Comment by Hunter-Nomad** [comment]
Cool))))
Good luck!
