### ISSUE TITLE
zmiany

### ISSUE THREAD

**Issue by darekmer** [zatorck/jquery-bootstrap-year-calendar#4]
Witam. Czy podpowiesz jak zrobić żeby twój kalendarz pokazywał zmiany (czterobrygadowy system pracy DDDDxPPPPxNNNNxx) w kolorze ? Dzięki z góry

**Comment by zatorck** [comment]
Niestety nie rozumiem, proszę o więcej szczegółów?

**Comment by darekmer** [comment]
Witam, sorki już nie aktualne. Pracuję na zmiany w systemie 4-brygadowym.
chciałem sobie zrobić grafik online w kolorze, cały rok na jednej stronie...
Ale teraz mam taki : http://members.upcpoczta.pl/d.tokarz32/
I raczej wyystarczy

**Comment by zatorck** [comment]
OK, zamykam. 

Pozdrawiam
