### ISSUE TITLE
appendText - date range

### ISSUE THREAD

**Issue by BigIWT** [zatorck/jquery-bootstrap-year-calendar#5]
Hi
Testing your year calendar - great so far !

With appendText function, I can add data to the calendar for single dates
$('.calendar').calendar('appendText', '', 2019, 3, 4);

Is there a way that I can highlight / append whole date ranges - goal would be to load from datasource and populate calendar with existing dates ?

example : 2019-03-04 to 2019-03-21 ??

thank you.

**Comment by zatorck** [comment]
Hello, 

Thank you mate!

I've added addRange function. Checkout documentation for more info.

Regards,
 Piotr
